name: Node.js CI

on:
  push:
    branches: 
      - test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/test' }}
    env:
      COMMIT_MSG: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm run lib
      - name: Set Environment File
        id: env
        run: |
          echo "COMMIT_MSG=${COMMIT_MSG}" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR from main branch
          title: Automated PR from main branch - ${{ env.COMMIT_MSG }}
          body: |
            ${{ env.COMMIT_MSG }}
            This is an automated PR from the main branch.
            Please review and merge if there are no issues.
          branch: pre-release

  test:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/test' }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && 
        github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm run clean
      - run: npm ci
      - run: npm run semantic-release
      - run: npx conventional-changelog -p angular -i CHANGELOG.md -s
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.my_GITHUB_TOKEN }}
